import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";
import Footer from "@/component/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-400">

        <header className="fixed z-100 px-30 w-full bg-white border-b-3 border-gray-300 ">
          <Header/>
        </header>
        <Marquee/>


      <main className="bg-gray-100 dark:bg-gray-800 mt-2">
        <div className="max-w-7xl mx-auto w-full">
          {children}

        </div>
      </main>

      <footer>
        <Footer/>
      </footer>

      </body>
    </html>
  );
}
