import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";

const notoSerifBengali = Noto_Serif_Bengali({
  
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-400">

        <header>
          <Header/>
          <hr className="border-2 border-t border-gray-300 mt-3" />
        </header>
        <Marquee/>


      <main className="bg-gray-100 dark:bg-gray-800 mt-3">
        <div className="max-w-7xl mx-auto w-full">
          {children}

        </div>
      </main>

      </body>
    </html>
  );
}
